apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice2
spec:
  hosts:
  - microservice2
  http:
  - route:
    - destination:
        host: microservice2
        subset: v1
      weight: 20
    - destination:
        host: microservice2
        subset: v2
      weight: 80
