---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice1-virtualservice
spec:
  hosts:
    - microservice1   # It will only accept traffic for microservice1 host, not as any other host like localhost
  http:
    - route:
        - destination:
            host: microservice1
            subset: v1
          weight: 5
        - destination:
            host: microservice1
            subset: v2
          weight: 95
