apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: microservice2
spec:
  host: microservice2
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2