apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice1-routing
spec:
  hosts:
  - microservice1
  http:
  - route:
    - destination:
        host: microservice1
        subset: v1
      weight: 90
    - destination:
        host: microservice1
        subset: v2
      weight: 10
