apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice3-v2
  labels:
    app: microservice3
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice3
      version: v2
  template:
    metadata:
      labels:
        app: microservice3
        version: v2
    spec:
      containers:
      - name: microservice3
        image: giodimagio/microservice3:v2
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     memory: 64Mi
        #     cpu: 250m
        #   limits:
        #     memory: 128Mi
        #     cpu: 500m
        ports:
        - containerPort: 5003
