apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v2
  labels:
    app: api-gateway
    version: v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-gateway
      version: v2
  template:
    metadata:
      labels:
        app: api-gateway
        version: v2
    spec:
      containers:
      - name: api-gateway
        image: giodimagio/api-gateway:v2
        imagePullPolicy: IfNotPresent
        # resources:
        #   requests:
        #     memory: 64Mi
        #     cpu: 250m
        #   limits:
        #     memory: 128Mi
        #     cpu: 500m
        ports:
        - containerPort: 9000
